name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
              
      - name: Checkout Node
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
        
      - name: Install dependencies
        run: |
          npm install
          
          
      - name: Build web-app
        run: |
          npm ci
          npm run build
      
          
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          
      - name: Set Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Instalar o Firefox e o GeckoDriver (Web Driver)
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
          sudo apt install firefox

          
      - name: Tests
        run: |
          pip install -U selenium
          cd testes
          python test.py
